# Server Configuration
server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always

# Spring Application
spring:
  application:
    name: idro

  data:
    mongodb:
      uri: mongodb://localhost:27017/idro_db
      database: idro_db
      auto-index-creation: true

# NASA API
nasa:
  api:
    key: eyJ0eXAiOiJKV1QiLCJvcmlnaW4iLCJzaWciOiJlZGxqd3RwdWJrZXlfb3BzIiwiYWxnIjoiUlMyNTYifQ...

# API Documentation (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Logging
logging:
  level:
    root: INFO
    com.india.idro: DEBUG
    org.springframework.data.mongodb: DEBUG


gemini:
  api:
    key: AIzaSyANZs4InPva-dOW9qHRwDinsyUm2RAK3n0
