# Server Configuration
server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always

# Spring Application
spring:
  application:
    name: idro

  # MongoDB Configuration
  data:
    mongodb:
      # For Local MongoDB Compass
      uri: mongodb://localhost:27017/idro_db
      # OR for MongoDB Atlas (Cloud), use this format:
      # uri: mongodb+srv://username:password@cluster0.xxxxx.mongodb.net/idro_db

      database: idro_db
      auto-index-creation: true

# API Documentation (Swagger)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Logging
logging:
  level:
    root: INFO
    com.india.idro: DEBUG
    org.springframework.data.mongodb: DEBUG